In [ ]:
print("Hello")

In [2]:
pip install pandas nltk scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: scipy>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

df = pd.read_csv("Resume.csv")

df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [4]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91702\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91702\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
stop_words = set(stopwords.words('english'))

def clean_resume(text):

    text = re.sub(r'[^a-zA-Z ]', '', text)

    text = text.lower()

    words = word_tokenize(text)

    filtered_words = [word for word in words if word not in stop_words]

    return " ".join(filtered_words)

In [6]:
df['cleaned_resume'] = df['Resume'].apply(clean_resume)

df[['Resume', 'cleaned_resume']].head()

KeyError: 'Resume'

In [7]:
print(df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [8]:
df['cleaned_resume'] = df['Resume_str'].apply(clean_resume)

df[['Resume_str', 'cleaned_resume']].head()

,Resume_str,cleaned_resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administratormarketing associatehr administ...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versati...
2,HR DIRECTOR Summary Over 2...,hr director summary years experience recruitin...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven dynamic...
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depar...

In [9]:
skills = [
    'python',
    'java',
    'sql',
    'machine learning',
    'data analysis',
    'html',
    'css'
]

In [10]:
def detect_skills(resume):

    found_skills = []

    for skill in skills:

        if skill in resume:
            found_skills.append(skill)

    return found_skills

In [11]:
df['skills_found'] = df['cleaned_resume'].apply(detect_skills)

df[['skills_found']].head()

      skills_found
0  [data analysis]
1               []
2               []
3               []
4               []

In [13]:
skills = [
    'python',
    'java',
    'sql',
    'machine learning',
    'data analysis',
    'deep learning',
    'data science',
    'excel',
    'power bi',
    'communication',
    'html',
    'css',
    'javascript',
    'react',
    'c++',
    'mongodb',
    'nodejs'
]

In [14]:
df['skills_found'] = df['cleaned_resume'].apply(detect_skills)

df[['skills_found']].head()

             skills_found
0         [data analysis]
1         [communication]
2                 [excel]
3  [excel, communication]
4                 [excel]

In [16]:
def calculate_score(skills):

    score = len(skills)

    if score > 10:
        score = 10

    return score

In [17]:
df['resume_score'] = df['skills_found'].apply(calculate_score)

df[['skills_found', 'resume_score']].head()

             skills_found  resume_score
0         [data analysis]             1
1         [communication]             1
2                 [excel]             1
3  [excel, communication]             2
4                 [excel]             1

In [18]:
top_candidates = df.sort_values(by='resume_score', ascending=False)

top_candidates[['Category', 'skills_found', 'resume_score']].head(10)

,Category,skills_found,resume_score
926,AGRICULTURE,"[python, java, sql, excel, communication, html...",10
297,INFORMATION-TECHNOLOGY,"[java, sql, excel, communication, html, css, j...",9
2199,BANKING,"[java, sql, deep learning, excel, communicatio...",9
2395,AVIATION,"[python, java, sql, excel, communication, html...",8
1356,AUTOMOBILE,"[java, sql, data analysis, excel, communicatio...",8
1091,SALES,"[java, sql, excel, communication, html, css, j...",7
2184,BANKING,"[java, sql, data analysis, communication, html...",7
1767,ENGINEERING,"[java, sql, excel, communication, html, css, r...",7
291,INFORMATION-TECHNOLOGY,"[python, java, sql, excel, html, css, javascript]",7
1303,DIGITAL-MEDIA,"[python, java, sql, excel, power bi, html, jav...",7

In [19]:
df.to_csv("Final_Resume_Output.csv", index=False)

print("Project Completed Successfully")

Project Completed Successfully